### ISSUE TITLE
Powerline on multiple lines in bash, and not showing top one on zsh

### ISSUE THREAD

**Issue by itsthatguy** [erikw/tmux-powerline#125]
So... I have it to a state where it's sort of working in bash. With ZSH, it's display is even worse.

 Any ideas?

![wtf-powerline](https://f.cloud.github.com/assets/1118006/58614/c9df0cec-5b78-11e2-82a1-059e702632be.jpg)
![wtf-powerline-zsh](https://f.cloud.github.com/assets/1118006/58615/c9dc506a-5b78-11e2-9e8e-8990dd012691.jpg)

**Comment by foobar** [comment]
I'm having this problem on Fedora 25, gnome terminal.

**Comment by yaway** [comment]
Same problem😕
I did as this answer said: https://stackoverflow.com/a/16174619/907353 and solved. 

` .tmux.conf`

```
# use UTF8
set -g utf8
set-window-option -g utf8 on
```

**Comment by Jeklah** [comment]
I have similar issue. I am using zsh and mintty. I have the left and right segments showing up properly, but the big green bar is still in the centre, doesn't look too bad...but if it's unintended, I am experiencing this bug.
