### ISSUE TITLE
Network monitor

### ISSUE THREAD

**Issue by erikw** [erikw/tmux-powerline#16]
A segment showing network usage statistics would be handy. Use ntop or iftop?

**Comment by ryran** [comment]
I see this happened way back in 2012... and even back then, @erikw said their `ifstat` didn't have a `-S` opt. None of the machines I've checked have that option...

```
ifstat -S
ifstat: invalid option -- 'S'
Usage: ifstat [OPTION] [ PATTERN [ PATTERN ] ]
   -h, --help           this message
   -a, --ignore         ignore history
   -d, --scan=SECS      sample every statistics every SECS
   -e, --errors         show errors
   -j, --json           format output in JSON
   -n, --nooutput       do history only
   -p, --pretty         pretty print
   -r, --reset          reset history
   -s, --noupdate       don't update history
   -t, --interval=SECS  report average over the last SECS
   -V, --version        output version information
   -z, --zeros          show entries with zero activity
   -x, --extended=TYPE  show extended stats of TYPE
```
... so this segment silently does nothing for me. What was the purpose of the `-S` option?

**Comment by erikw** [comment]
@ryran I see that the `ifstat` from Homebrew has the `-S` option.
https://github.com/Homebrew/homebrew-core/blob/master/Formula/ifstat.rb

If you are on Linux, maybe see if the segment `ifstat_sys` works better for you?

https://github.com/erikw/tmux-powerline/blob/master/segments/ifstat_sys.sh
