### ISSUE TITLE
mailcount exit wiht code 1

### ISSUE THREAD

**Issue by LiaoPengyu** [erikw/tmux-powerline#168]
++ export TMUX_POWERLINE_SEG_MAILCOUNT_MBOX_INBOX=
++ TMUX_POWERLINE_SEG_MAILCOUNT_MBOX_INBOX=
++ eval TMUX_POWERLINE_SEG_MAILCOUNT_MAILCHECKRC=/home/liao/.mailcheckrc
+++ TMUX_POWERLINE_SEG_MAILCOUNT_MAILCHECKRC=/home/liao/.mailcheckrc
++ '[' -z /home/liao/.mailcheckrc ']'
++ '[' -z gmail ']'
++ local count
++ case "$TMUX_POWERLINE_SEG_MAILCOUNT_MAILBOX_TYPE" in
+++ __count_gmail
+++ local tmp_file=/tmp/tmux-powerline_liao/gmail_count.txt
+++ local tmp_wgetrc=/tmp/tmux-powerline_liao/tmp_wgetrc.txt
+++ local override_passget=false
+++ '[' '!' -f /tmp/tmux-powerline_liao/gmail_count.txt ']'
+++ let 'interval=60_10'
+++ shell_is_osx
+++ [[ linux == \o\s\x ]]
+++ shell_is_bsd
+++ [[ linux == \b\s\d ]]
+++ [[ linux == \o\s\x ]]
+++ shell_is_linux
+++ [[ linux == \l\i\n\u\x ]]
++++ stat -c %Y /tmp/tmux-powerline_liao/gmail_count.txt
+++ last_update=1370401451
++++ date +%s
+++ '[' 6559 -gt 600 ']'
+++ '[' -z secret ']'
+++ which wget
+++ '[' 0 -ne 0 ']'
+++ echo -e 'user=secret@mail.com\npassword=secret'
++++ wget -q -O - https://mail.google.com/a/gmail.com/feed/atom --config /tmp/tmux-powerline_liao/tmp_wgetrc.txt
++++ grep fullcount
++++ sed 's/<[^0-9]_>//g'
+++ mail=
+++ rm /tmp/tmux-powerline_liao/tmp_wgetrc.txt
+++ '[' '' '!=' '' ']'
+++ return 1
++ count=
++ local exitcode=1
++ '[' 1 -ne 0 ']'
++ return 1
+ output=
+ local exit_code=1
+ unset -f run_segment
+ '[' 1 -ne 0 ']'
+ debug_mode_enabled
+ '[' -n true -a true '!=' false ']'
+ local seg_name=mailcount.sh
+ echo 'Segment '\''mailcount.sh'\'' exited with code 1. Aborting.'
Segment 'mailcount.sh' exited with code 1. Aborting.
+ exit 1

I can login the https://mail.google.com/a/gmail.com/feed/atom in my chrome, using the usename and the "2 step-verification and application-specific password"

**Comment by erikw** [comment]
I'm closing this stale issue due to age.
