### ISSUE TITLE
Inside the tmux  shell can not be displayed powerline?

### ISSUE THREAD

**Issue by dongweiming** [erikw/tmux-powerline#172]
I follow the readme installed tmux-powerline, the status bar with the powerline effect, but my shell like this：
![screen shot 2013-07-19 at 10 23 17 am](https://f.cloud.github.com/assets/841395/823655/58afad74-f01a-11e2-8d4e-fb4212494556.png)

When I do not use tmux shell is like this:

![screen shot 2013-07-19 at 10 25 35 am](https://f.cloud.github.com/assets/841395/823658/8ba68e46-f01a-11e2-98aa-067b4ea95b10.png)

I use powerline is by [zsh-prompt-powerline](https://github.com/Valodim/zsh-prompt-powerline), Can you help me find out where the problem?

**Comment by erikw** [comment]
I'm closing this stale issue due to age.
