### ISSUE TITLE
[APPEARANCE] Right status bar arrow missing some part

### ISSUE THREAD

**Issue by mengzhuo** [erikw/tmux-powerline#174]
Here is my status bar
Apparently there is something missing in the right bar

my config is default and the powerline version is the 5a3818aba0e90fc527c2cb42f1ebb19123339c8f

```
set-option -g status-right "#(~/.tmux/tmux-powerline/powerline.sh right)"
```

![2013-08-06 10 05 26](https://f.cloud.github.com/assets/885662/914540/509f7894-fe3e-11e2-94c7-8369d38ed1a5.png)
![left](https://f.cloud.github.com/assets/885662/914541/5453d39a-fe3e-11e2-86e0-80d4fb460a46.png)

**Comment by erikw** [comment]
I'm closing this stale issue due to age.
