### ISSUE TITLE
np_itunes.script does not work on yosemite

### ISSUE THREAD

**Issue by KidFeng** [erikw/tmux-powerline#191]
np_itunes.script does not work on my macbook pro retina.

it works fine before, maybe not compatible with yosemite.

i got this message when i run the script:

```
execution error: An error of type -10810 has occurred. (-10810)
```

**Comment by MoOmEeN** [comment]
looks like spotify broke something.
here is the workaround. 
https://www.unifiedremote.com/tutorials/how-to-get-spotify-version-spotify-101xxx-on-mac-osx
worked for me :)

**Comment by MoOmEeN** [comment]
sorry, I didn't notice that you are asking about itunes script ;)
anyway, maybe it is worth switching to spotify ;)

**Comment by erikw** [comment]
I'm closing this stale issue due to age.
