### ISSUE TITLE
mailcount gmail wrong xml tag parsing

### ISSUE THREAD

**Issue by mullakhmetov** [erikw/tmux-powerline#194]
On OS X 10.10.2 got invalid gmail_count file. I fixed it by changing grep pattern ebta. Line 143 in mailcount.sh:
```bash
mail=$(wget q -O -https://mail.google.com/a/${TMUX_POWERLINE_SEG_MAILCOUNT_GMAIL_SERVER}/feed/atom --config "$tmp_wgetrc" | grep -E -m 1 -o "<fullcount>(.*)</fullcount>"| sed -e 's,.*<fullcount>\([^<]*\)</fullcount>.*,\1,g')

**Comment by erikw** [comment]
Make it a pull request, then it will be easier too see what is changed. Is grep on OS X different in this case you mean? Then maybe it has to be wrapped in an if depending on OS.

**Comment by mullakhmetov** [comment]
Ok, done.
