### ISSUE TITLE
Determining Ideal Configuration Values for L&R Status Lengths in .tmux.conf 

### ISSUE THREAD

**Issue by her** [erikw/tmux-powerline#200]
Hey all 

What is the protocol for determining ideal status lengths in the .tmux.conf file? My reading of the documentation isn't revealing many answers. Currently my status line seems to work with various configured lengths ranging from (30-60 L & R). 

How can one determine the ideal lengths? As of right now I'm just opening my .tmux.conf file and editing the lengths, reopening tmux and observing the changes. Rinse Repeat. 

Is there anyway we can add a small mention in the Installation README on how to determine the correct values? 

Thanks :)
 
iTerm2, OS X (10.10.13)

**Comment by yukie-** [comment]
Okay so following this [Issue #166](https://github.com/erikw/tmux-powerline/issues/166) and the suggestion in it I a command from the [Debugging section](https://github.com/erikw/tmux-powerline#debugging) of the README:

$ bash -x ~/bin/tmux/scripts/powerline/powerline.sh left|right

This returned 743 lines of output D: 

I should mention that my status line *isn't broken*, I'm just a little lost on how to determine the appropriate values for my shell. 

Thanks again everyone

**Comment by her** [comment]
I'm going to close this, since... well, it's solved for the most part. :+1:
