### ISSUE TITLE
the tmux-powerline will disappear

### ISSUE THREAD

**Issue by netcan** [erikw/tmux-powerline#202]
When I started tmux, it can display the status bar , and then disappeared , back to green .
![screenshot - 08102015 - 10 26 26 am](https://cloud.githubusercontent.com/assets/11377070/9158505/88c9f0a6-3f4a-11e5-83ba-aa7257b3f0f4.png)

**Comment by farfeduc** [comment]
I have the same issue. I'm using bash on debian jessie with xterm.

when I launch 
```bash
bash powerline.sh left```
 I get a "failed to connect to server: Connection refused" error.

same with the "right" option

**Comment by inamiy** [comment]
Same issue occurs in MacOS 10.11 + bash + (terminal or iTerm2). 

Here's a screen capture when status bar is shown before it quickly disappears.
It seems like tmux-server is not ready.

<img width="1273" alt="2016-04-23 18 12 34" src="https://cloud.githubusercontent.com/assets/138476/14760443/06b9462a-097f-11e6-8b11-614d3dad6469.png">
