### ISSUE TITLE
git not found

### ISSUE THREAD

**Issue by eduOS** [erikw/tmux-powerline#203]
Contrary to #41, I run into an issue where the powerline disappears instantly everytime I enter a git repo. 

Sometimes the right half of the status line sparks randomly when I run Vim for which I've installed the Vim-powerline and Vimux, and sometims it shows only the central words which tell me how many panes are created in the some situation. The powerline just dies whenever I navigate the zsh command line to a repo. 

Thanks, if any suggestions are given.

**Comment by erikw** [comment]
I'm closing this stale issue due to age.
