### ISSUE TITLE
Powerline on multiple lines in gnome-terminal

### ISSUE THREAD

**Issue by xiaoyanghaitao** [erikw/tmux-powerline#206]
Hey,I installed tmux-powerline today and I finded the tmux display like this 
![tmux_with_powerline](https://cloud.githubusercontent.com/assets/12468484/9853355/c806b612-5b35-11e5-896f-50d4bbc0878d.png)

I am using fedora 22 and the $LANG=zh_CN.UTF-8, $TERM=xterm-256color.
I also use 'alias tmux="tmux -2"' in my ~/.bashrc

Because I installed tmux and tmux-powerline today,so I followed the steps of guide on github.
Here's my ~/.tmux.conf:
set-option -g status on
set-option -g status-interval 2
set-option -g status-utf8 on
set-option -g status-justify "centre"
set-option -g status-left-length 60
set-option -g status-right-length 90
set-option -g status-left "#(~/tmux-powerline/powerline.sh left)"
set-option -g status-right "#(~/tmux-powerline/powerline.sh right)"
set-window-option -g window-status-current-format "#[fg=colour235, bg=colour27]⮀#[fg=colour255, bg=colour27] #I ⮁ #W #[fg=colour27, bg=colour235]⮀"
bind C-[ run '~/tmux-powerline/mute_powerline.sh left'      # Mute left statusbar.
bind C-] run '~/tmux-powerline/mute_powerline.sh right'     # Mute right statusbar.
I confirm the path of shell is right.

**Comment by xiaoyanghaitao** [comment]
I also find when I delete 'set-option -g status-left "#(~/tmux-powerline/powerline.sh left)"' and 'set-option -g status-right "#(~/tmux-powerline/powerline.sh right)"' it will look like this
![tmux_with_powerline2](https://cloud.githubusercontent.com/assets/12468484/9853381/dc22ff7a-5b35-11e5-9e06-bd7706133494.png)
but it looks like I haven't use powerline.

**Comment by lighter** [comment]
+1.I am same.

**Comment by clijunky** [comment]
The -g in "set-option -g status-left" sets that globally.  Leaving it out will allow it to only be on one line. 

*Note: If the set-option status-left is in your always sourced .tmux.conf, it will still act global, even if not set for that.  I used a separate .tmux.powerline.conf and source that manually on the first line only.  That way subsequent lines are not powerlined.

Source: I use this multiline and had to sort that out myself.
