### ISSUE TITLE
Separator glyphs do not appear properly in windows

### ISSUE THREAD

**Issue by mousavian** [erikw/tmux-powerline#213]
I am using tmux inside [Babun](https://github.com/babun/babun) in Windows 7.
I have changed the font from "Consolas" to few other fonts but nothing changed.

Here's a screenshot of what I see:
![capture](https://cloud.githubusercontent.com/assets/317322/13074729/785da56e-d4e1-11e5-83dc-d7abeb7cd790.PNG)

Any idea about how I can fix this?

**Comment by nomaed** [comment]
@mousavian Have you tried any of the Powerline fonts?
