### ISSUE TITLE
zsh - Not work PS1 configuration

### ISSUE THREAD

**Issue by rskull** [erikw/tmux-powerline#221]
~/.zshrc

```
PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'
```

Not work properly.

![2016-04-24 22 23 09](https://cloud.githubusercontent.com/assets/886268/14767917/27a0b8de-0a6d-11e6-8030-e508cfa5aa08.png)

This has been resolved.

```
PROMPT+=`$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")`
```

Not work in the first way.
Does this problem will only me?

**spec**
- zsh 5.0.8
- tmux 2.1

**Comment by rezmuh** [comment]
I experienced the same issue on zsh 5.2 and tmux 2.2

Prior changing to your solution, I got a *lost server* message whenever I'm in tmux. It has since gone away after I changed PROMPT line to yours.

**Comment by co1inlee** [comment]
only write `[ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD"` to .zshrc! It works to me!
