### ISSUE TITLE
Unknown option: status-utf8 

### ISSUE THREAD

**Issue by Jeansen** [erikw/tmux-powerline#244]
:TmuxlineSnapshot generates a file containing `set -g status-utf8 "on"` which causes tmux to shout: `/.tmux.conf:16: unknown option: status-utf8.`

**Comment by erikw** [comment]
I think you posted this issue in the wrong project. I don't know what `:TmuxlineSnapshot`is.  :)

**Comment by Jeansen** [comment]
Oh boy. My bad! I mistakenly was in the wrong browser tab. Anyway, thank's for the quick reply! :-)
