### ISSUE TITLE
prefix_mode_indicator - copy mode indicator

### ISSUE THREAD

**Issue by dominikduda** [erikw/tmux-powerline#246]
Hello,

Writing regarding recently merged plugin.

I found variable indicating copy mode in TMUX - `pane_in_mode`.

Yet I am not able to write triple condition (`if client_prefix; elif pane_in_mode; else;`). Right now it is written [like so](https://github.com/erikw/tmux-powerline/pull/245/commits/e02d6de0b1bc58a2e00000a61cc31411a76ea04f#diff-9626b62741321a0eef4c626e9e11b4afR10) with this strange string conditional `?conditional_val,if_true,if_false`.

Is nesting this string conditional (I can not find anything about that syntax) possible?

**Comment by erikw** [comment]
In the tmux manual ($ man tmux) section `FORMATS` it says

```
Conditionals are available by prefixing with ‘?’ and separating two alternatives with a comma; if the specified variable exists and is not zero, the first alternative is chosen, otherwise the second is used.  For example ‘#{?session_attached,attached,not
attached}’ will include the string ‘attached’ if the session is attached and the string ‘not attached’ if it is unattached, or ‘#{?automatic-rename,yes,no}’ will include ‘yes’ if automatic-rename is enabled, or ‘no’ if not.
```

I've not tried it but it might be possible to chain like

```
?conditional_val,?conditional_val2,if_true_cond_1_and_cond2,if_true_cond1_not_cond2,if_false_cond1
```

**Comment by dominikduda** [comment]
Okay, I figured out a solution. I will create PR in the evening CET.

Thanks for your response!
