### ISSUE TITLE
Not looks as pretty as vim-airline

### ISSUE THREAD

**Issue by eromoe** [erikw/tmux-powerline#253]
Hi, 

I am using msys2 on windows 7

After I setup `tmux-powerline`, it looks a little ugly , not so pretty as in vim.

Comparison:

left is tmux,  right is original
![image](https://user-images.githubusercontent.com/3938751/27947321-f49504a8-6327-11e7-8c25-7d088ced93b9.png)

Looks like some render error ? Any way to solve it?

**Comment by SynapticSage** [comment]
You have to turn on 256 color mode in your tmux.conf

`set -g default-terminal "screen-256color"`

**Comment by eromoe** [comment]
Of course, 

In vim:
![image](https://user-images.githubusercontent.com/3938751/30260190-7378f9b0-96f8-11e7-83f4-158efb275ea0.png)

In tmux:
![image](https://user-images.githubusercontent.com/3938751/30260245-c1aeca38-96f8-11e7-83c5-355404c94b0e.png)

**Comment by aaronky** [comment]
What does `echo $TERM`  output in tmux?

**Comment by eromoe** [comment]
In tmux:
screen-256color

In normal console:
xterm

**Comment by eromoe** [comment]
Today see this  https://github.com/altercation/solarized/issues/159#issuecomment-5566892

> Solution for me was set -g default-terminal "screen-256color" in .tmux.conf and xterm-256color in the iTerm 2 settings. 

1. `set -g default-terminal "screen-256color"` in .tmux.conf
2. `TERM=xterm-256color` in msys2 's  `~/.bashrc`

would work. 

But I found another problem  if I enter and exit vim,  tmux's status-line would be replaced by vim's .
