### ISSUE TITLE
Enabling WANIP gives HTML output

### ISSUE THREAD

**Issue by backendr** [erikw/tmux-powerline#256]
This only started happening today. I havent updated. Not quite sure the reason why.
My WANIP segment now gives some html/javascript output.

Enabled:
<img width="1680" alt="screen shot 2017-10-20 at 17 57 20" src="https://user-images.githubusercontent.com/26419373/31830340-348f0ab4-b5c0-11e7-88db-a397ca99b793.png">

Disabled:
<img width="1680" alt="screen shot 2017-10-20 at 18 00 12" src="https://user-images.githubusercontent.com/26419373/31830459-8b4ad216-b5c0-11e7-890f-2def18985994.png">

Here is the debug output:
```
+++ cat /tmp/tmux-powerline_matthewlowe/wan_ip.txt
++ wan_ip='<html>
<head>
<script>window.close();</script>
</head>
<body>
</body>
</html>'
++ '[' -z '<html>
<head>
<script>window.close();</script>
</head>
<body>
</body>
</html>' ']'
++ '[' -n '<html>
<head>
<script>window.close();</script>
</head>
<body>
</body>
</html>' ']'
++ echo 'ⓦ <html>
<head>
<script>window.close();</script>
</head>
<body>
</body>
</html>'
++ return 0
+ output='ⓦ <html>
<head>
<script>window.close();</script>
</head>
<body>
</body>
</html>'
+ local exit_code=0
+ unset -f run_segment
+ '[' 0 -ne 0 ']'
+ '[' -n 'ⓦ <html>
<head>
<script>window.close();</script>
</head>
<body>
</body>
</html>' ']'
+ powerline_segment_contents[$segment_index]=' ⓦ <html>
<head>
<script>window.close();</script>
</head>
<body>
</body>
</html> 
```

**Comment by erikw** [comment]
I'm closing this stale issue due to age.
