### ISSUE TITLE
tmux-powerline weather bug

### ISSUE THREAD

**Issue by JoeAsir** [erikw/tmux-powerline#266]
## when I actived the weather in default.sh, the bar would continue be updating and never stop. I have no idea what's going on and how to fix it up.
![image](https://user-images.githubusercontent.com/14145765/41831355-195dfb2a-7879-11e8-8782-81484b7e6879.png)

**Comment by wu-nerd** [comment]
Same problem here, it just happened, everything works fine before with the same configuration. 
Kill tmux or restart the computer changed nothing, delete  TMUX_POWERLINE_SEG_WEATHER_LOCATION variable it's back to normal.

tmux 2.7 
macOS 10.13.6 (17G65)

**Comment by wu-nerd** [comment]
Found workaround in https://github.com/erikw/tmux-powerline/issues/242:
Comment https://github.com/erikw/tmux-powerline/blob/e214721694661448176580433fd563f82542545a/segments/weather.sh#L128 and set condition_symbol to a common character, like a space.

It works, but then i can not reproduce this problem. Weird.

**Comment by JoeAsir** [comment]
Really works! Thx
