### ISSUE TITLE
Multiple status line printed(Still Same issue as #1652)

### ISSUE THREAD

**Issue by dannyk0104** [erikw/tmux-powerline#268]
![p](https://user-images.githubusercontent.com/23534258/48973688-4d7acc80-f00b-11e8-818a-7b29358e2d3c.PNG)

The problem is same as #1652. 
I tried all the solutions(work around), but still could not fix it. 

I put following on .tmux_conf file
`# use UTF8
set -g utf8
set-window-option -g utf8 on`

following to .bashrc file
`export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8`

and modified powerline.json file like following 
`		"time": {
			"before": ""
		}`

I am using windows subsystem linux with bash. 
Without powerline, it works fine. 

I really want to have powerline for my Tmux!!
Please help!!

**Comment by dxuehu** [comment]
same issue~

**Comment by dxuehu** [comment]
> same issue for me. It was working fine but I noticed this started happening maybe 1-2 weeks ago :( makes it unusable for me

**Comment by erikw** [comment]
Based on the configuration details you posted, I think you meant to post this issue at https://github.com/powerline/powerline

This is another tmux powerline project
