### ISSUE TITLE
Is this project still "deprecated"?

### ISSUE THREAD

**Issue by IngoHeimbach** [erikw/tmux-powerline#270]
The README states that this project is deprecated in favor of the new [unifying powerline](https://github.com/powerline/powerline) but the last commit in the new project is from 11 Nov 2018 and it has only one tmux specific segment. It seems to me that the new powerline project is not adopted by many users. Is the new project dead or does anyone know what the current status is?

**Comment by erikw** [comment]
Hey! The README is still correct. I allow pull requests from people that use it still, but from my side there is no longer effort put in to the project. I recommend using the from README linked powerline python project :)
