### ISSUE TITLE
Missing up arros icon

### ISSUE THREAD

**Issue by niv280** [erikw/tmux-powerline#273]
Hi,
I got all the icons and that works great, but i am missing the icon that arrow point up ( not sure how to describe it).

![image](https://user-images.githubusercontent.com/61157132/120101864-f3fe3600-c150-11eb-850e-193fd7dbe985.png)

I checked that the encoding is UTF-8, and install the powerline fonts but this icon still not appear.

Also i can see that icon in the powerlineSymbols font:
![image](https://user-images.githubusercontent.com/61157132/120101883-11cb9b00-c151-11eb-9ebd-f8b19ad4f00d.png)

**Comment by erikw** [comment]
@niv280 I'm not sure which icon is missing. Did you find a solution to this?

**Comment by niv280** [comment]
No, I didn't find the solution.
But i eventually stopped use tmux so that kinda solve it
