### ISSUE TITLE
Missing lan ip

### ISSUE THREAD

**Issue by afreisinger** [erikw/tmux-powerline#275]
Missing lan ip on status bar. Only show me N/A
I'm not sure if shell.sh exports the variables correctly.

**Comment by erikw** [comment]
Hey,

you can debug by sourcing

https://github.com/erikw/tmux-powerline/blob/master/segments/lan_ip.sh

directly in your shell and call the function defined in it to see what is going on :)

**Comment by afreisinger** [comment]
Hello erik !
Quick test on Sunday morning. I put the contents of shell.sh in lan_ip.sh and it worked ...

**Comment by erikw** [comment]
Is it the same machine that you also run tmux-powerline on?

**Comment by bplx** [comment]
2022 and i'm still having this same issue along with some other funnies. The LAN ip won't show up and the WAN ip is cut off a little bit at the end of it. I have attempted to increase the line width in the left but it did nothing.
Please, send help!

**Comment by erikw** [comment]
What operating systems are you both running? The logic depends on if it's Linux or macos/BSD as seen here on this line

https://github.com/erikw/tmux-powerline/blob/master/segments/lan_ip.sh#L4

To debug this segment, you can do like this:

```console
$ bash
$ source segments/lan_ip.sh
$ set -x
$ run_segment
$ set +x
```

I just made a little fix for macOS
https://github.com/erikw/tmux-powerline/commit/dada6968f1a4d3af7b918cde3321e196ebbefbea
If you are on mac, try out the latest version on `master` branch:)
