### ISSUE TITLE
Shows docker0 ip instead of wlo1

### ISSUE THREAD

**Issue by kamidzuua** [erikw/tmux-powerline#293]
Encountered problem with `lan_ip.sh` segment. Showed docker0 interface ip over wlo1 ip.
 
That change fixed that for me. I'm not huge bash script maestro, but I think that extra `/` instructed to remove `lo` symbols from all array elements, which broke script since `ip addr show w1` returns `Device "w1" does not exist.`

Changing that fixed issue for me, but I'm not sure if that fixes it for everyone.

```bash
# segments/lan_ip.sh

all_nics=(${all_nics[@]//lo/})	 # original line 17

all_nics=(${all_nics[@]/lo/})     # removing slash fixed the issue 

```

**Comment by erikw** [comment]
Thank you @kamidzuua 

It's hard to know if it will break someone's system, as they look all quite different and things like interface name changes when new OS versions comes out. If it does break something, we'll fix!
