### ISSUE TITLE
Replace names automatically by icons

### ISSUE THREAD

**Issue by DavidEGx** [erikw/tmux-powerline#295]
It would be nice to get some program names replaced by their icon (as an option). So instead of:

![image](https://user-images.githubusercontent.com/1056061/198349303-e85756ea-0c5b-4430-aad2-a981d505cfb1.png)

we could automatically have:

![image](https://user-images.githubusercontent.com/1056061/198349596-e8d87362-931b-41f9-938a-642f375ff516.png)

or even:

![image](https://user-images.githubusercontent.com/1056061/198349723-1809e7dc-01b5-4c06-a245-5194e20be1ee.png)

vi, vim, nvim replaced by 
sql, mysql, psql, etc replaced by 
so on and so forth

Icons in those examples come from: https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib/i_dev.sh

**Comment by erikw** [comment]
Cool idea!

I could imagines this being developed as a complete TPM plugins in itself, as it would be independent of tmux-powerline.If such a plugins existed, it would work automatically with tmux-powerline. With this reasoning I'd close this issue here:)
