### ISSUE TITLE
How do you get the equivalent of tmux default color

### ISSUE THREAD

**Issue by purplefishies** [erikw/tmux-powerline#296]
Hi,

While configuring this, I find that I can't actually get a color that matches tmux's "default" color...which in the case of a translucent window, allows me to get transparency . 

Curious what value we can set a segment to do get this effect.

**Comment by erikw** [comment]
@purplefishies run the [color_palette.sh](https://github.com/erikw/tmux-powerline/blob/main/color_palette.sh) to see what colors you have to chose from :)

**Comment by purplefishies** [comment]
Hi Erik,

No, it's not a color issue. It's the fact that you can't specify "default" as a color...something you can do in tmux and it allows you honor the back color erase "bce".

I have a fix that allows this "default" color to be specified.

```
__print_colored_content() {
    bgcolor="$2"
    fgcolor="$3"
    if [[ $bgcolor == "default" ]] ; then
        BGCOLOR=$bgcolor
    else
	[ "${bgcolor:0:1}" = "#" ] && BGCOLOR="$bgcolor" || BGCOLOR="colour$bgcolor"
    fi

    if [[ "$fgcolor" == "default" ]] ; then
        FGCOLOR=$fgcolor
    else
	[ "${fgcolor:0:1}" = "#" ] && FGCOLOR="$fgcolor" || FGCOLOR="colour$fgcolor"
    fi

    echo -n "#[fg=${FGCOLOR},bg=${BGCOLOR}]"
    echo -n "$1"
    echo -n "#[default]"
}

```

Let me know if I should submit a PR ?

**Comment by erikw** [comment]
Ah now I see what you mean @purplefishies. This make sense, please make a PR! :)
