### ISSUE TITLE
tmuxline not following g:airline_left_sep / g:airline_right_sep

### ISSUE THREAD

**Issue by bendavis78** [erikw/tmux-powerline#297]
If I customize my airline separators to use different glyphs, I would expect the tmuxline conf to do the same. Currently it uses the triangle symbols regardless of airline setting.

For example, setting the following options:

    let g:airline_left_sep = "\uE0B4"
    let g:airline_right_sep = "\uE0B6"

Gives this result:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/324392/200034580-2c77fcf4-eb81-4302-aaea-26f3c843e287.png">

**Comment by erikw** [comment]
Hey, I'm not sure that you posted this in the right repo. There's not connection between this project and airline :)

**Comment by bendavis78** [comment]
Oops, my mistake!
