### ISSUE TITLE
Allow tmux session info to be customized

### ISSUE THREAD

**Issue by tnkhanh** [erikw/tmux-powerline#298]
In `segments/tmux_session_info.sh` , the format is fixed to `'#S:#I.#P'` : [ tmux_session_info.sh](https://github.com/erikw/tmux-powerline/blob/aaef83e1c4a6616a067eeac8fb3d483d053808a2/segments/tmux_session_info.sh#L1-L7)

Although powerline user can change the format in this file, it's better to have the format modifiable in `.tmux-powerlinerc` (I think).

For example, `date.sh` has the format modifiable in `export TMUX_POWERLINE_SEG_DATE_FORMAT="%d %b %+4Y"` in the rc file. Maybe we can do something similar to `tmux_session_info.sh`

(Or we can change `date.sh` to be modifiable at source like `tmux_session_info.sh`, it's weird they are different)

**Comment by erikw** [comment]
A PR is welcomed, there are plenty of examples in https://github.com/erikw/tmux-powerline/tree/main/segments how this can be done :)

**Comment by tnkhanh** [comment]
I submitted a PR to resolve this issue

**Comment by erikw** [comment]
Fixed by https://github.com/erikw/tmux-powerline/pull/299
