### ISSUE TITLE
Changing default tmux-powerline status settings

### ISSUE THREAD

**Issue by TheSast** [erikw/tmux-powerline#305]
While I think the default status settings are fine, they are definetly not great.
I'm specifically talking about these:
https://github.com/erikw/tmux-powerline/blob/f8f22cd96bd3c0b10b3ac641113997f40873f86f/main.tmux#L15-L17

1. I know a few people that have their status only show up in certain cases (e.g. prefix pressed, window/session menu) and this would conflict with that setup.
1. The [time](https://github.com/erikw/tmux-powerline/blob/main/segments/time.sh) and [utc_time](https://github.com/erikw/tmux-powerline/blob/main/segments/utc_time.sh) segments can be formatted to show seconds, which would unintuitively refresh only every other second.
1. I think that tmux-powerline can work and look great even when the window list is left or right justified, I personally use it everyday with the former. 
Also before I updated tmux to 3.3a I personally experienced some strange behaviour from `status-justify "centre"` (incorrect and inconsistent alignment on using no segments/semi-static segments) that didn't arise when using `status-justify "absolute-centre"` which I would reccomend as the replacement default.

I think these issues could be resolved by having the option to set these parameter in the rc file.

**Comment by erikw** [comment]
Hello, thanks for the suggestions!

Letting `status-interval` and `status-justify` be overridden from the default values in the rcfile could be a great addon I think. 

f8f22cd96bd3c0b10b3ac641113997f40873f86f shows how it can be done like `TMUX_POWERLINE_MUTE_LEFT_KEYBINDING_DEFAULT`

Regarding the default `status-interval`, 1 second makes sense as a default.

Regarding `status on`, does tmux-powerline make sense to use with any other value than `on` here? 🤔 I currently can't see it but maybe there is.

PRs are welcome :)

**Comment by TheSast** [comment]
> Regarding `status on`, does tmux-powerline make sense to use with any other value than `on` here? 🤔 I currently can't see it but maybe there is.

Yeah, it can.
For example, my professor uses something akin to:
```
bind -n C-b  set-option -g status "on" \; switchc -Tprefix \; run-shell -Cbd5 'set-option -g status "off"'
```
Which makes their status line appear temporarely for 5 seconds when hitting the prefix key.
They use this since they work on a laptop with limited screensize.
