### ISSUE TITLE
last.fm not working with now playing segment 

### ISSUE THREAD

**Issue by GamerGirlandCo** [erikw/tmux-powerline#307]
i've inputted my username into the config file, but nothing shows up in my status line. for what it's worth, last.fm appears to have completely removed the `1.0` api endpoint, which the segment uses. so maybe someone could look into bringing it [up to date](https://www.last.fm/api/intro) ?

**Comment by erikw** [comment]
Thank you @GamerGirlandCo for reporting. I've not used last.fm with the NP segment for along time. I updated it to use the 2.0 API.

To use the 2.0 API, it's not necessary to create your own API key.  Please see the changes made in this commit ce523459661cb327b99ae124ccd7e4061c5cddad

You need to make sure that `jq` is installed on your computer, and create an API application at https://www.last.fm/api/account/create and copy the key to your tmux-powerline config in the new configuration `$TMUX_POWERLINE_SEG_NOW_PLAYING_LASTFM_API_KEY`

For me it's working now. Let me know if it's not working for you.
