### ISSUE TITLE
Fresh install simply shows a solid, full-width line

### ISSUE THREAD

**Issue by adaviloper** [erikw/tmux-powerline#308]
![image](https://user-images.githubusercontent.com/16654653/236652216-5c9543ba-083a-4742-a832-2594dad834f1.png)

After adding the plugin line to my `tmux.conf` file and using the `prefix+I` command from `tpm` to install `tmux-powerline`, the status bar updates to the above rather than the default from the README.md screenshots.
I'm not entirely sure what I'm missing and I've also gone through the ambiguous character check from #125 and I'm still getting the same result as in the image with the only thing showing being the window titles fully centered.

Terminal: iTerm2
Shell: zsh
Editor: NeoVim
OS: MacOS Monterey 12.6.4
Font: JetBrainsMono NerdFont

Directory Structure:
```
- ~/.config
    - tmux
        - plugins
            - tmux-powerline
            - tmux-sensible
            - tpm
        - tmux.conf
        - tmux.conf.local
    - tmux-powerline
        - themes
            - my-theme.sh
        - config.sh
```

I don't imagine the font is the issue as I've tried a Powerline font with the same result. I've also uninstalled everything and was able to start from the barebones Tmux status bar before installing `tmux-powerline`.

**Comment by erikw** [comment]
Hello @adaviloper,

are you on a stable iTerm2 version or beta/nightly? I currently have an issue myself with iTerm2 beta versions and nerd fonts: https://gitlab.com/gnachman/iterm2/-/issues/10879


Looking at that old issue you linked:
* Do you have UTF8 enbaled in your terminal, https://github.com/erikw/tmux-powerline/issues/125#issuecomment-311919274
* And `$TERM` set properly?


What happens when you run powerline directly in the terminal, any output?

For me it looks like
``` bash
$ ~/.config/tmux/plugins/tmux-powerline/powerline.sh left
#[fg=colour234,bg=colour148] general:2.0 #[default]#[fg=colour148,bg=colour235]ÓÇ∞#[default]%
```
(powerline symbols not rendered on GitHub of course)

or try that with `bash -x ...` as described here: https://github.com/erikw/tmux-powerline#debugging

**Comment by adaviloper** [comment]
@erikw 

I'm on a stable build using version 3.4.19.
`$TERM` is set to `xterm-256color.
Character encoding is set to `Unicode (UTF-8)`

The output from that matches the values being assigned in the true condition of the `if patched_font_in_use; then` block.

I think we're honing into the issue here, though I'm not sure which step I've missed.

When trying to run the command directly, I get the following:
```
└─> ~/.config/tmux/plugins/tmux-powerline/powerline.sh left                                                                                                  14:20:23
/Users/<username>/.config/tmux/plugins/tmux-powerline/powerline.sh: line 3: realpath: command not found
/Users/<username>/.config/tmux/plugins/tmux-powerline/powerline.sh: line 5: ./lib/headers.sh: No such file or directory
/Users/<username>/.config/tmux/plugins/tmux-powerline/powerline.sh: line 7: powerline_muted: command not found
/Users/<username>/.config/tmux/plugins/tmux-powerline/powerline.sh: line 8: process_settings: command not found
/Users/<username>/.config/tmux/plugins/tmux-powerline/powerline.sh: line 9: check_arg_side: command not found
/Users/<username>/.config/tmux/plugins/tmux-powerline/powerline.sh: line 13: print_powerline: command not found
```

I did a fresh install to verify that all of the files are still there.

**Comment by erikw** [comment]
@adaviloper ah it seems to be that `realpath` is not available. I will try to simply stop using it.

Could you check out the branch `fix/308` and see if it works then for you?

```bash
$ cd ~/.config/tmux/plugins/tmux-powerline/powerline.sh
$ git fetch
$ git switch fix/308
```

**Comment by adaviloper** [comment]
![image](https://user-images.githubusercontent.com/16654653/236703083-a4d21087-3199-46b0-b477-8f843e5b35d1.png)

That seemed to immediately fix it. I'm only showing the center and right half to not show more sensitive information on the left)

**Comment by erikw** [comment]
Great! The fix is merged, you can switch back to the `main` branch.
