### ISSUE TITLE
How to init on Mac?

### ISSUE THREAD

**Issue by Erimus-Koo** [erikw/tmux-powerline#317]
The `generate_rc.sh` does not work on my Mac, and return 
```
env: bash\r: No such file or directory
```

My `tmux.conf` is `~/.tmux.conf`, and my plugins folder is `~/.tmux/plugins/tmux-powerline`.

Is there some variable name like `#{cpu_percentage}`, is there a list?

**Comment by erikw** [comment]
Hi, have you installed all prerequisites especially bash? On mac you can do `$ brew install bash` with Homebrew.

I think you are looking to use this segment:

https://github.com/erikw/tmux-powerline/blob/main/segments/cpu.sh


Follow the instructions in the README and it should be cleared how to enable this segment in your own theme configuration :)

**Comment by Erimus-Koo** [comment]
> Hi, have you installed all [prerequisites](https://github.com/erikw/tmux-powerline#requirements) especially bash? On mac you can do `$ brew install bash` with Homebrew.
> 
> I think you are looking to use this segment:
> 
> https://github.com/erikw/tmux-powerline/blob/main/segments/cpu.sh
> 
> Follow the instructions in the README and it should be clear how to enable this segment in your own theme configuration :)

Hi, is this bash from brew different from the `/bin/bash`?

I've used a plugin
```
set -g @plugin 'tmux-plugins/tmux-cpu'
```
so I used `#{cpu_percentage}` before. 
And I want to know how to use variables in powerline, because I am stuck at the stage of configuration, and can not see any sample.

Is the powerline included all the segments while installing? or if I need to install them one by one?

And how should it be used in the .tmux.conf? Is there some sample?
like:
```
# right ----------
set -g status-right-length 200
set -g status-right '#[fg=green,bg=black]#(tmux-mem-cpu-load -q -l 0 -r 0 -c -g 0 -i 2)#[fg=brightblack,bg=black] %A %m-%d %H:%M'
```

**Comment by erikw** [comment]
Again, the README has the answer to all questions above :).

Make sure the Bash version is meeting the requirements. Easiest to install latest version with Homebrew.


This plugin is not working like you think, there are no variables and you don't configure the statubsr manuelly. If you follow the README there will be example of how to configure it.

https://github.com/erikw/tmux-powerline#configuration

Please open up this issue again if after reading and following the README it does not answer the questions :).

**Comment by Erimus-Koo** [comment]
I've resolved, all the problems caused by the `git config autocrlf`. 
After resetting the head and with the correct LF, it works.
Thank you for your responses, and I hope this helps anyone who encounters a similar situation.

**Comment by erikw** [comment]
Ah that explains the `\r` in the error message! It looked like you were on a Windows computer even though you wrote Mac, it was confusing.

Thanks for sharing the fix!

**Comment by Erimus-Koo** [comment]
And there's some difference with the readme.

## Config file
At first, I run:
```
~/.config/tmux/plugins/tmux-powerline/generate_rc.sh
```
got this hint:
```
Default configuration file generated to: /Users/erimus/.tmux-powerlinerc.default
Copy/move it to "/Users/erimus/.tmux-powerlinerc" and make your changes.
```
I moved it to `~/.config/tmux-powerline/.tmux-powerlinerc`, and not works. 🤯
`mv ~/.tmux-powerlinerc` worked. 🎊

I don't know what happens to the path, it's different to the readme.
Are `config.sh` and `.tmux-powerlinerc` equal?

### my env

I've exported XDG_CONFIG_HOME in `~/.zshrc`, and:
```
echo $XDG_CONFIG_HOME
/Users/erimus/.config
```

The plugins folder is set in tmux.conf
```
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'
```
The plugin was installed in `~/.config/tmux/plugins/tmux-powerline`.


## How to define the segment details?
For example,  
how can I define the color of mem and cpu separately in tmux-mem-cpu-load?

**Comment by erikw** [comment]
The plugin try to be smart preferring XDG paths but still supporting the old legacy homedir path.

https://github.com/erikw/tmux-powerline/blob/main/config/paths.sh

Could you run the command like this and share the output please? :)

```bash
bash -x ~/.config/tmux/plugins/tmux-powerline/generate_rc.sh
```

Oh actually I think I know the problem. This plugin is written in bash and not ZSH. You must set `XDG_CONFUG_HOME` in a shell startup script that is used by non-interactive bash invocations, I think `~/.profile` would work.

tmux-mem-cpu-load appears to be a different project than this, not related. But there's a cpu segment you can use with this plugin as well.

**Comment by Erimus-Koo** [comment]
Yes, you are right. I added the `XDG_CONFIG_HOME` in `~/.zshrc`.
`~/.profile`, `~/.bashrc`, `~/.bash_profile`, there're many config settings on Mac :)
