### ISSUE TITLE
TMUX_POWERLINE_SEG_NOW_PLAYING_MUSIC_PLAYER_DEFAULT is misleading

### ISSUE THREAD

**Issue by embe221ed** [erikw/tmux-powerline#319]
`__process_settings` function in the `now_playing.sh` script doesn't set the default value of the `TMUX_POWERLINE_SEG_NOW_PLAYING_MUSIC_PLAYER` which is set to `"spotify"`. I would recommend either adding the line to `__process_settings` that assigns the default value if the `TMUX_POWERLINE_SEG_NOW_PLAYING_MUSIC_PLAYER` is empty or replace the `TMUX_POWERLINE_SEG_NOW_PLAYING_MUSIC_PLAYER_DEFAULT` with empty string.

**Comment by erikw** [comment]
> I would recommend either adding the line to `__process_settings` that assigns the default value if the `TMUX_POWERLINE_SEG_NOW_PLAYING_MUSIC_PLAYER` is empty

This sounds correct to me. A PR would be welcome!

**Comment by embe221ed** [comment]
#320
