### ISSUE TITLE
Reload after modifying my theme

### ISSUE THREAD

**Issue by tnkhanh** [erikw/tmux-powerline#322]
How do I reload after modifying my theme? Sourcing `.tmux.conf` again does not help.
So `tmux-powerline` has `set-hook -g sessions-created` to `init`. It only reloads if I create a new session, That's a bit awkward.
Is there a faster way to reload?
Edit: It is `session-created` (singular)!

**Comment by tnkhanh** [comment]
> 
> I can't see that this plugin set `sessions-created` anywhere. Where did you see this?

@erikw  It's in the file you show me, lol [main.tmux](https://github.com/erikw/tmux-powerline/blob/d75110f3568bcca2c6e1ebcdafd978fbe7d1dbda/main.tmux#L33C16-L33C16)

I think something resets on `session-created` because this happens to me:
* Change `TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR` or `TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR` in your theme file
* The change does not take effect until you do `<Prefix>:new` to create a new session

**Comment by erikw** [comment]
> So `tmux-powerline` has `set-hook -g sessions-created`

Ah sry I was lazy grep'd on the misspelling here, `sessions-created`, and thus did not find it. I see, `session-created` is used indeed!


> There is no need for a reload. On every status bar re-draw the plugin is run again from scratch. The default is to re-draw the status bar every second, unless this is changed in your `tmux.conf` (set [here](https://github.com/erikw/tmux-powerline/blob/main/main.tmux#L16), [default value](https://github.com/erikw/tmux-powerline/blob/a62d4f132592753c2a2e6cd69b2a3983d9c7c8b5/config/defaults.sh#L8))

This should still be true; every status interval (1 second), tmux will just execute the powerline script again and the latest version of the tmux-powerline configuration file and theme will be used. 

If you disable a segment in the theme and save the file, it should disappear within 1 second, unless this is changed in your tmux.conf (set [here](https://github.com/erikw/tmux-powerline/blob/main/main.tmux#L16), [default value](https://github.com/erikw/tmux-powerline/blob/a62d4f132592753c2a2e6cd69b2a3983d9c7c8b5/config/defaults.sh#L8))

If the segment disappears, we know the theme is properly reloaded :) 

When I change `TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR` in my theme, it changes almost directly (<1sec) in the status bar.

**Comment by tnkhanh** [comment]
Sry, I didn't notice I misspelled :(
I'm testing different colors so it's a bit inconvenient.
But yeah, I can live with it for now. Thanks :)

**Comment by tnkhanh** [comment]
@erikw Can we reopen this so that someone might come across it and fix it? Also see if others might have the same issue.

**Comment by erikw** [comment]
Added a note in the README about this.

**Comment by erikw** [comment]
Fixed by https://github.com/erikw/tmux-powerline/pull/362#issuecomment-1992618595

**Comment by tnkhanh** [comment]
> @erikw
> 
> > > There is no need for a reload.
> 
> I think, there is. I have changed the VISIBILITY from "on" to "2" to get the dual-line, and that required me to restart tmux session.

This is a very long conversation where we concluded that it needed a reload. There is a bugfix in the last comment but I haven't checked and it seems to rework the whole plugin
