### ISSUE TITLE
Wrong information on powerline if a second terminal has focus

### ISSUE THREAD

**Issue by fnzr** [erikw/tmux-powerline#323]
If I have different terminals running different tmux sessions, both powerlines show the information of the currently focused terminal, instead of the information associated with the terminal powerline is on. I find this very confusing if I have multiple terminals open on different sessions or working dirs.

I made no changes to the default theme other than commenting out a few segments.

I am uncertain if this is working as intended, but is there a config I can set to change this behavior? Maybe only update the powerline if the terminal has focus?

Gif shows the problem.

![powerline-tmux](https://github.com/erikw/tmux-powerline/assets/5471818/89c43b1e-292b-4bdf-b114-b98822dedce2)

**Comment by erikw** [comment]
The tmux status bar is global and can thus only show information to the currently focuses terminal. I don't know any way around this in tmux. Thus it's working as intended :-)
