### ISSUE TITLE
Add now_playing.sh support for Tidal

### ISSUE THREAD

**Issue by Drew-Daniels** [erikw/tmux-powerline#327]
Hello, I'm really enjoying using the `now_playing` segment in `tmux-powerline`.

I wanted to ask if it would be ok if I start working on a PR to add functionality to display `now_playing` data when [Tidal](https://tidal.com/) is in use? I don't normally use Spotify, so adding support for this would be great for my use case.

**Comment by erikw** [comment]
Hey, sry slow reply.

Yes that would be great. Just make sure to follow how the other players are implemented in terms of functionality and how they are configured. :)

**Comment by erikw** [comment]
I'm closing this issue here for now, but a PR is still welcome!
