### ISSUE TITLE
README.md out of date?

### ISSUE THREAD

**Issue by christianparpart** [erikw/tmux-powerline#330]
Section Config: https://github.com/erikw/tmux-powerline#config-file

seems to be wrong, or at least out of date. I have zero prior knowledge of tmux-powerline (nor tpm), but i barely made it working. Now, the problem seems to be I cannot configure it. Despite trying to follow the config section in the README.md, which is partly wrong, I feel like my changes to `~/.tmux-powerlinerc` are ignored.

Most importantly, the segments are showing way to much, like everything (so it feels), so I tried to find not to display that much, like, disabling some things, like ifstat.sh, but I seem not to find the documentation that tells me how to. - Do you have any hints for me?

Many thanks.

**Comment by erikw** [comment]
The README is updated to not reference the old configuration file `~/.tmux-powerlinerc` anymore, only the new `~/.config/tmux-powerline/config.sh`.

**Comment by benjaminmikiten** [comment]
I ended up here, trying to follow the README, and hope to add some context for anyone else who comes looking.

After some digging, I found that when `paths.sh` tries to set the `$TMUX_POWERLINE_RCFILE` it looks to see if `~/.config/tmux-powerline` is set, and defaults to the old `.tmux-powerlinerc` if it's not.

If you've installed this with `tpm`, you may find that `~/.config/tmux-powerline/config.sh.default` hasn't been created, as `~/.config/tmux-powerline` will be in `~/.config/tmux/plugins/tmux-powerline` isntead, causing the `paths.sh` function above to use a `.tmux-powerlinerc` isntead.

**Comment by erikw** [comment]
@benjaminmikiten interesting. Maybe it's time to remove support for that old configuration file `~/.tmux-powerlinerc` to make the code easier and more stable.

Could you test if this PR solves the problem? 
https://github.com/erikw/tmux-powerline/pull/335

You can check the PR out with

```bash
$ cd you/tmux-powerline/clone
$ git fetch origin pull/335/head:fix-330
```

**Comment by benjaminmikiten** [comment]
Yes, I'll confirm these changes -- just one moment.

**Comment by benjaminmikiten** [comment]
Running `./generate_rc` throws an error from line 107 of `rcfile.sh` saying that `config.sh.default` doesn't exist.

**Comment by erikw** [comment]
@benjaminmikiten Thank you for testing. I could replicate this by removing my `~/.config/tmux-powerline` dir.

Could you update the PR branch to the latest commit and try again please?

**Comment by benjaminmikiten** [comment]
That did it! I now have a `~/.config/tmux-powerline`. Thank you!
