### ISSUE TITLE
symbols

### ISSUE THREAD

**Issue by klapvogn** [erikw/tmux-powerline#332]
Hi,

I just tried to install this tmux-powerline. and when I look at the IP ADDRESS I only have a square and no symbols ?

And I installed it like this :

**.tmux.conf**
 `set -g @plugin 'erikw/tmux-powerline'`

and when I look at https://github.com/erikw/tmux-powerline#configuration

I don't have : 
the config.sh
`~/.config/tmux/plugins/tmux-powerline/generate_rc.sh
mv ~/.config/tmux-powerline/config.sh.default ~/.config/tmux-powerline/config.sh
$EDITOR ~/.config/tmux-powerline/config.sh`

**Comment by erikw** [comment]
Hey, should should execute the script on the first line there from the README
`$ ~/.config/tmux/plugins/tmux-powerline/generate_rc.sh`

then the configuration will be generated to `~/.config/tmux-powerline/config.sh.default` which you can copy to use.
