### ISSUE TITLE
how to remove segment? 

### ISSUE THREAD

**Issue by irreallich** [erikw/tmux-powerline#333]
Hi,
   My display requirement is to be able to display a pwd as long as possible, but the width of the monitor is limited, so I only need to be able to display the window and pwd. What if I can do this?

In addition, can the status line below display two layers, one for normal information and one for pwd?

**Comment by erikw** [comment]
Use a custom theme to configure to only use a psd segment for example. Give more space to it maybe by setting the window list to right or left instead of center, look at the generated config file for all width and placement options!

Having a double status bar is not supported by tmux.
