### ISSUE TITLE
Change window status color on activity?

### ISSUE THREAD

**Issue by mwpardue** [erikw/tmux-powerline#336]
I'm sorry, I'm sure I'm missing something simple, but I'm trying to figure out how to change the colors of a window's status label when there is activity. I don't want to just invert it but rather change to entirely different colors. Ultimately I want to change the activity icon as well, but that's another issue.

I can get the colors to change by doing the below:
```
if [ -z $TMUX_POWERLINE_WINDOW_STATUS_FORMAT ]; then
	TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
    "#{?window_activity_flag,#[fg=colour16 bg=colour88],#[$(format regular)]}" \
		"  #I#{?window_flags,#F, } " \
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN" \
		" #W "
	)
fi
```

What I can't figure out is why this doesn't color the bold separators at either end. Instead of getting the pretty status bar label changed from end to end, I just get the text label changed and the separators are colored the default color of the rest of the status bar See below for an example. 

<img width="405" alt="image" src="https://github.com/erikw/tmux-powerline/assets/88067650/14f71ce4-63a8-4b2d-9c82-027c1c01fa3c">

Can somebody please help me figure out what I'm doing wrong? I've been working on this long enough that I'm sure I'm repeating myself now and just need at least a nudge in the right direction. 

Thanks in advance for any help anybody can provide!!

**Comment by erikw** [comment]
Hey, exactly where do you put these changes?

**Comment by erikw** [comment]
Hmm I wonder if this is also a current limitation similar to

https://github.com/erikw/tmux-powerline#changign-tmux_powerline_default_ground_color-does-not-have-effect

With my own testing, by restarting the tmux session, changes to `TMUX_POWERLINE_WINDOW_STATUS_FORMAT` did take effect.

**Comment by mwpardue** [comment]
> This seems to be a current limitation similar to
> 
> https://github.com/erikw/tmux-powerline#changign-tmux_powerline_default_ground_color-does-not-have-effect
> 
> With my own testing, by restarting the tmux session, changes to `TMUX_POWERLINE_WINDOW_STATUS_FORMAT` did take effect.

I don't think that's exactly this, though I certainly could be wrong. I did see this issue of FORMAT not changing during an active session when I first started trying to change the activity background, so now each time I make a change I actually kill all active sessions, make the changes while outside of tmux, double check that no sessions are still active, then create a new session. And I do see the changes I make, it just doesn't theme the separators at either end of the window status label with activity. 

In this screen snippet you can see it just themes the areas with text (or spaces) and not the separators at either end.

![image](https://github.com/erikw/tmux-powerline/assets/88067650/9bfbcda8-a264-493d-b4ce-9775ab8ce422)


I probably should have described the screen snippet a bit more as well. Sorry. In that snippet I have window 1 open. That blue color is my default color for active windows, inactive windows are a black background with blue text. I'm trying to have windows with activity change the label to, in this example, a red background with orange text. (Ugly, I know. Just a set of obvious test colors for now.) In the example screen snippet I have `top` running in window 2 and when it detects the activity the label goes from blue on black (inactive) to yellow on red, except for the separators on either end.

If you put this inside your tmux-powerline theme, does it theme the separators on windows with activity?

```
if [ -z $TMUX_POWERLINE_WINDOW_STATUS_FORMAT ]; then
	TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
    "#{?window_activity_flag,#[fg=colour16 bg=colour88],#[$(format regular)]}" \
		"  #I#{?window_flags,#F, } " \
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN" \
		" #W "
	)
fi
```

**Comment by mwpardue** [comment]
> This seems to be a current limitation similar to
> 
> https://github.com/erikw/tmux-powerline#changign-tmux_powerline_default_ground_color-does-not-have-effect
> 
> With my own testing, by restarting the tmux session, changes to `TMUX_POWERLINE_WINDOW_STATUS_FORMAT` did take effect.

i just realized this was closed after your last response. Can we reopen it? I don't think it's exactly what you're referring to, as noted in my last response. Sorry for any confusion.

**Comment by erikw** [comment]
Ah I see, it's not about the need for recreating the tmux session.

At this point I'm not able to give you further support on this exact configuration that you are after, other than that the `TMUX_POWERLINE_WINDOW_STATUS_FORMAT` is used one status like this in tmux-powerline:
https://github.com/erikw/tmux-powerline/blob/6da8967029d32d278febf7ac075bcf55f4252044/lib/powerline.sh#L77

If you really want to get this configuration to work, I think the best is to follow the code path for rendering and figure out what's going on :) . In regards to the styling of the window list, I don't think it's really anymore than what I just linked above.

**Comment by mwpardue** [comment]
> Ah I see, it's not about the need for recreating the tmux session.
> 
> At this point I'm not able to give you further support on this exact configuration that you are after, other than that the `TMUX_POWERLINE_WINDOW_STATUS_FORMAT` is used one status like this in tmux-powerline:
> 
> https://github.com/erikw/tmux-powerline/blob/6da8967029d32d278febf7ac075bcf55f4252044/lib/powerline.sh#L77
> 
> If you really want to get this configuration to work, I think the best is to follow the code path for rendering and figure out what's going on :) . In regards to the styling of the window list, I don't think it's really anymore than what I just linked above.

So would you say that it should be changing the color of those separators and that I must have something else going on that is preventing it? I've tried following the code through and I'm getting a bit more of a handle on it, but I'm still unclear on how precisely those separators should get themed. Can you answer a couple basic questions for me to confirm I'm on the right track?

<img width="321" alt="image" src="https://github.com/erikw/tmux-powerline/assets/88067650/dc9a80d5-d8db-44bd-b4bd-1c5986dab94c">


Given the above screenshot, and assuming "Billing" is the active window, would I be correct in saying the separator that is being indicated by the arrow would be part of the second window's label, the one running top? 

If that is correct, do you think I should focus in on the TMUX_POWERLINE_WINDOW_STATUS_FORMAT section like I have been, or should I focus on the TMUX_POWERLINE_WINDOW_STATUS_STYLE section of my theme? I'm not completely clear on the difference between _STYLE and _FORMAT at this point. It seems that you can do everything with _FORMAT that you can do with _STYLE.

I'm still pretty new with tmux, and really any kind of programming, and now this has gotten under my skin and I want to find a solution. Just want to make sure I'm approaching it correctly.

**Comment by erikw** [comment]
Thanks for clarifying. At this point I don't have the capacity to dig in to this unfortunately, but maybe at a later point or if someone else drops by :).

I'm sure though that with some debugging those questions are answerable :)

**Comment by mwpardue** [comment]
> Thanks for clarifying. At this point I don't have the capacity to dig in to this unfortunately, but maybe at a later point or if someone else drops by :).
> 
> I'm sure though that with some debugging those questions are answerable :)

OK, I think I know what the problem is now. I can't count. lol

Where I thought it wasn't theming the right number of cells I now see that it's theming exactly what it should. The part that's not themed is part of the adjacent window's status label, specifically it's the background of the last bold separator and/or the foreground of the next window's bold separator. I'm not sure there's any good way to theme those to a different color based on the status of the neighboring window, but even if there is it's probably more difficult than it's worth. I think we can close this topic since it seems my request doesn't really mesh well with the Powerline style of window labels.

Sorry for the confusion...

**Comment by voodookiidoo** [comment]
> > Thanks for clarifying. At this point I don't have the capacity to dig in to this unfortunately, but maybe at a later point or if someone else drops by :).
> > I'm sure though that with some debugging those questions are answerable :)
> 
> OK, I think I know what the problem is now. I can't count. lol
> 
> Where I thought it wasn't theming the right number of cells I now see that it's theming exactly what it should. The part that's not themed is part of the adjacent window's status label, specifically it's the background of the last bold separator and/or the foreground of the next window's bold separator. I'm not sure there's any good way to theme those to a different color based on the status of the neighboring window, but even if there is it's probably more difficult than it's worth. I think we can close this topic since it seems my request doesn't really mesh well with the Powerline style of window labels.
> 
> Sorry for the confusion...

hey man, you figured something out?

**Comment by erikw** [comment]
Fixed by https://github.com/erikw/tmux-powerline/pull/362#issuecomment-1992618595
