### ISSUE TITLE
Configuration as described in README does not work out of the box

### ISSUE THREAD

**Issue by Xenion1987** [erikw/tmux-powerline#341]
I've installed `tmux-powerline` as described via `tpm`.Then, Ive tried to follow the configuration steps as described in the README.md and tried to generate the rc-file:

```
mrvn@odroidh2:~$ ~/.tmux/plugins/tmux-powerline/generate_rc.sh
/home/mrvn/.tmux/plugins/tmux-powerline/config/paths.sh: line 14: [: missing `]'
getconf: Unrecognized variable `DARWIN_USER_DIR'
/home/mrvn/.tmux/plugins/tmux-powerline/lib/rcfile.sh: line 107: /home/mrvn/.config/tmux-powerline/config.sh.default: No such file or directory
Default configuration file generated to: /home/mrvn/.config/tmux-powerline/config.sh.default
Copy/move it to "/home/mrvn/.config/tmux-powerline/config.sh" and make your changes.
```

The main issue seems to be the missing value of `${XDG_CONFIG_HOME}`:

```
mrvn@odroidh2:~$ echo $XDG_CONFIG_HOME

mrvn@odroidh2:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Also, the directory `~/.config` did not exist when trying to configure `tmux-powerline`.

```
mrvn@odroidh2:~$ pwd
/home/mrvn
mrvn@odroidh2:~$ ls -lAh .config
ls: cannot access '.config': No such file or directory
mrvn@odroidh2:~$ echo $XDG_CONFIG_HOME

mrvn@odroidh2:~$
```

So the first step "generating your own configuration file" does not work due to the wrong path:

```
mrvn@odroidh2:~$ ~/.config/tmux/plugins/tmux-powerline/generate_rc.sh
-bash: /home/mrvn/.config/tmux/plugins/tmux-powerline/generate_rc.sh: No such file or directory
mrvn@odroidh2:~$
```

You are describing two different paths for the `tmux-powerline` files:

1. `~/.config/tmux-powerline`
1. `~/.config/tmux/plugins/tmux-powerline`

So I need to create symlinks that are pointing to the described paths:
```sh
mkdir -p ~/.config/tmux/plugins && \
ln -s ~/.tmux/plugins/tmux-powerline ~/.config/tmux-powerline && \
ln -s ~/.tmux/plugins/tmux-powerline ~/.config/tmux/plugins/tmux-powerline
```
```
mrvn@odroidh2:~$ tree .config
.config
├── tmux
│   └── plugins
│       └── tmux-powerline -> /home/mrvn/.tmux/plugins/tmux-powerline
└── tmux-powerline -> /home/mrvn/.tmux/plugins/tmux-powerline
```

From then on, generating the config file seem to work, but throws an error:

```
mrvn@odroidh2:~$ ~/.config/tmux/plugins/tmux-powerline/generate_rc.sh
/home/mrvn/.config/tmux/plugins/tmux-powerline/config/paths.sh: line 14: [: missing `]'
getconf: Unrecognized variable `DARWIN_USER_DIR'
Default configuration file generated to: /home/mrvn/.config/tmux-powerline/config.sh.default
Copy/move it to "/home/mrvn/.config/tmux-powerline/config.sh" and make your changes.
mrvn@odroidh2:~$ ls -lAh /home/mrvn/.config/tmux-powerline/config.sh.default
-rw-rw-r-- 1 mrvn mrvn 9,9K Okt 31 22:55 /home/mrvn/.config/tmux-powerline/config.sh.default
mrvn@odroidh2:~$
```

So I modified the mentioned line from:

```sh
if [ ! -d "$TMUX_POWERLINE_RCDIR" && ! -L "$TMUX_POWERLINE_RCDIR" ]; then
```

to

```sh
if [ ! -d "$TMUX_POWERLINE_RCDIR" ] && [ ! -L "$TMUX_POWERLINE_RCDIR" ]; then
```

to fix the if clause. But it would not create the directory `mkdir -p "$TMUX_POWERLINE_RCDIR"` either, because the conditions would fail due to the missing `~/.config/tmux-powerline` directory if not created manually as described above.

---

Also using a custom theme seems to be described wrong:
https://github.com/erikw/tmux-powerline/blob/main/README.md?plain=1#L141

This would create a new file named `my-theme.sh.default`, but we've already created and/or modified the file `my-theme.sh`. Or is there any function that checks for an `.default` extension?

---

Is the manual "wrong" or am I missing something?

**Comment by erikw** [comment]
Oh, I’ll take a look later today. Might be related to just merged PR 
https://github.com/erikw/tmux-powerline/pull/339

**Comment by erikw** [comment]
> So I modified the mentioned line from:

You're correct. I updated accordingly
https://github.com/erikw/tmux-powerline/commit/26f1c54e9af035968021a73eda095f88f67b30f6
thanks!
