### ISSUE TITLE
sharing my config and battery segment

### ISSUE THREAD

**Issue by embe221ed** [erikw/tmux-powerline#344]
Hey,

I wanted to share few things that I've changed in my config as I find them pretty good.
I'll prepare two PRs for these in case you find it good.

1. changed the `battery.sh` script to improve the icons displayed
the heart icon is replaced with battery/plug icon to better reflect the current state. I've changed the color of the icon to red in case the battery level is lower than 50%.
The most improved version is for MacOS, but I've also done some improvements to the Linux version.

2. my "bubble" theme
replaced separators, updated colors, for example Spotify colors are the same as in Spotify logo, Github - as well.

few screenshots:
1. charging
<img width="2048" alt="Screenshot 2023-11-06 at 12 13 00" src="https://github.com/erikw/tmux-powerline/assets/26097838/a72d0429-1fab-421c-8523-21a38f9846dc">

2. not charging, 100-80%
<img width="2048" alt="Screenshot 2023-11-06 at 12 13 11" src="https://github.com/erikw/tmux-powerline/assets/26097838/1e8cdab0-1934-442f-89ae-f9e3605bdcea">

3. not charging, 80-50%
<img width="2048" alt="Screenshot 2023-11-06 at 12 14 20" src="https://github.com/erikw/tmux-powerline/assets/26097838/54f9bc9b-4fe2-4f7e-b46f-c7e9b586401c">

4. not charging, less than 50%
<img width="2048" alt="Screenshot 2023-11-06 at 12 13 58" src="https://github.com/erikw/tmux-powerline/assets/26097838/7bb9a7af-7e75-487c-a6b6-1b383db993cb">

**Comment by erikw** [comment]
Hey, those sounds like cool improvements :)

**Comment by marsjane** [comment]
I tried yours config, but when I reload config, it shows "'~/.tmux/plugins/tpm/tpm' returned 1", any idea how to debug, where is the error info?

**Comment by marsjane** [comment]
Really cool!

**Comment by marsjane** [comment]
btw, how to set the background of tmux same with the status bar background?

**Comment by embe221ed** [comment]
it depends on the terminal emulator you use. I am using kitty, and here is the repo for that theme: https://github.com/catppuccin/kitty
(kitty/macchiato is used on the screenshots)

**Comment by marsjane** [comment]
After i changed the terminal theme to macchiato, and I create a new tmux session, it seems still not match? I guess it is status bar bg, I didn't set it in the tmux conf, it is a tmux session on remote machine, any idea why the bar shows a different bg?
![Shot 2023-11-07 at 18 32 52@2x](https://github.com/erikw/tmux-powerline/assets/45665172/7fd0cedb-062b-4086-b00c-894b7e59fa95)

**Comment by embe221ed** [comment]
maybe restarting the `tmux-powerline` will work?
try to play with `$thm_bg` variable inside the `themes/bubble_theme.sh` and check if it results with changed color of the background

**Comment by embe221ed** [comment]
+ maybe the terminal in your remote session handle only 8bit colors?

**Comment by marsjane** [comment]
Thanks. I tried to set `set -g status-bg "#24273A"` and reload the config, nothing changed. So I guess it is possible that `maybe the terminal in your remote session handle only 8bit colors`, do you know how to confirm this?

**Comment by embe221ed** [comment]
I think you should check the env variable $TERM

**Comment by marsjane** [comment]
```
~ ❯ echo $TERM
xterm-256color
 ```
really weird...

**Comment by embe221ed** [comment]
maybe you have the `TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR` variable set somewhere else?

**Comment by marsjane** [comment]
```
rg TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR
config/tmux-powerline/themes/powerline-theme.sh
15:TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'235'}
config/tmux-powerline/themes/bubble-theme.sh
60:TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-$thm_bg}
```
but i tested your theme is good locally. So your theme should be fine, just some bug in my remote machine

**Comment by embe221ed** [comment]
that's strange. Hopefully, you will find the reason! 🤞

**Comment by erikw** [comment]
Resolved with:
* https://github.com/erikw/tmux-powerline/pull/346
* https://github.com/erikw/tmux-powerline/pull/345
