### ISSUE TITLE
Anyone knows, how to stop turining cool arrow-shaped segment of status bar into rectangles?

### ISSUE THREAD

**Issue by voodookiidoo** [erikw/tmux-powerline#347]
### Discussed in https://github.com/erikw/tmux-powerline/discussions/342

<div type='discussions-op-text'>

<sup>Originally posted by **voodookiidoo** November  1, 2023</sup>
If i have an active proccess, such as vim or cat, the tab in the status bar that respresents the window will be rectengular shaped, instead of arrow-like. How do I fix that?</div>

**Comment by erikw** [comment]
See https://github.com/erikw/tmux-powerline/discussions/342#discussioncomment-7449867

**Comment by xx4h** [comment]
Closing this, see discussion mentioned above.
