### ISSUE TITLE
Changing background color of the tmux window list

### ISSUE THREAD

**Issue by Luh-code** [erikw/tmux-powerline#356]
I can't figure out how to change the background color of the tmux window list in the middle. It is stuck on this green color, it kind of looks like a color from gruvbox, which is the theme I tried configuring the bar to, but I don't think I set it to be that anywhere...

Here's a gist of my theme, which is just a modification of the default: https://gist.github.com/Luh-code/e2135c02ce8fa8f6d33aa780654d2744

And here's how it looks like currently: ![2024-01-26_14_13_16](https://github.com/erikw/tmux-powerline/assets/60015267/bde541b9-1d40-46f3-8a03-13d5c0e74b7d)

**Comment by Luh-code** [comment]
Update: Still haven't figured it out. I've re-riced my whole system since this post, but the problem still persists. Also it is a thing on all themes. Including default and bubble.
![image](https://github.com/erikw/tmux-powerline/assets/60015267/87f90cab-24bc-452a-bf14-88d77924e260)

**Comment by erikw** [comment]
Fixed by https://github.com/erikw/tmux-powerline/pull/362#issuecomment-1992618595
