### ISSUE TITLE
Powerline init not executed on first session creation

### ISSUE THREAD

**Issue by StopMotionCuber** [erikw/tmux-powerline#358]
Hey, I would like to utilise the fancy window list, but that doesn't work right now for me, as it seems the 
`tmux set-hook -g session-created "run-shell '${TMUX_POWERLINE_DIR_HOME}/powerline.sh init'"` doesn't seem to run on initial session creation.

## Steps to reproduce
Assumption: `tmux-powerline` is configured properly, according to README
1. Close all tmux sessions
2. Start a new tmux session with `tmux`
3. Wait for powerline to load

## Expected result
The window list is not the default window list and has a powerline style

## Actual result
The window list has the default style

## Workaround
Starting a _second_ session leads to the expected result.

## Further notes
I think this is caused by the `session-created` hook running _before_ loading all the plugins and stuff. It would be fixed by adding `${TMUX_POWERLINE_DIR_HOME}/powerline.sh init` to the end of the `main.tmux` file. I'm not sure whether there would still be a reason for keeping the hook then.
I also don't understand the reason to go for a hook here in the first place.

**Comment by erikw** [comment]
Fixed by https://github.com/erikw/tmux-powerline/pull/362#issuecomment-1992618595
