### ISSUE TITLE
Support tmux-suspend in mode_indicator segment

### ISSUE THREAD

**Issue by creinig** [erikw/tmux-powerline#367]
Feature request:

[tmux-suspend](https://github.com/MunifTanjim/tmux-suspend) adds a "custom mode" where the prefix key is always passed through to a nested tmux. tmux-powerline's mode-indicator segment doesn't support this yet.

The linked PR lets mode-indicator display "SUSPEND" instead of the normal/prefix indicator if tmux-suspend is installed and activated.

**Comment by xx4h** [comment]
This can be closed, as it is merged and tested/working.
