### ISSUE TITLE
powerline fails to start in termux

### ISSUE THREAD

**Issue by creinig** [erikw/tmux-powerline#369]
Under [termux](https://termux.dev/) (Linux shell on android) tmux-powerline fails to start. The cause for this is a hardcoded reference to `/tmp/` in `config/paths.sh`. termux has to model the entire system inside of a normal directory, so absolute paths (like `/tmp`) generally don't work. As workaround for that, the environment variable `TMPDIR` points to the correct path to use.

The linked PR applies a fix to `paths.sh`.

**Comment by erikw** [comment]
Fixed by https://github.com/erikw/tmux-powerline/pull/370
