### ISSUE TITLE
Add dual-line status bar support

### ISSUE THREAD

**Issue by xx4h** [erikw/tmux-powerline#379]
As i personally like to use a lot of segments and always have a fair amount of windows open, often it gets to the limits of a one-line status bar. So i added dual-line status bar support to tmux-powerline, already using it for a couple of days
now and not seeing any issues.

Even though this is expected to be working on Mac/BSD as well, testing on Mac/BSD is still to be done, i'll test this the coming days, but would also be happy if anyone wants to give it a try.

**Comment by xx4h** [comment]
Successfully tested on BSD (GhostBSD)

![image](https://github.com/erikw/tmux-powerline/assets/2880059/d10cba5a-8791-4619-9d0c-a444c8ff9a57)

**Comment by erikw** [comment]
@xx4h I forgot to mention in the PR to update the change log, for upgrading users:

https://github.com/erikw/tmux-powerline/commit/62f58f03dbfd959d1fe47b62ab182cec1ceaa00d
