### ISSUE TITLE
Status Justification always behaves as relatively centered

### ISSUE THREAD

**Issue by jnzigg** [erikw/tmux-powerline#381]
**Environment:**
- Debian 13
- tmux 3.3a
- zsh 5.9
- Minimal tmux config

```
set -g status-position top
set -g base-index 1

set -g prefix C-e
unbind C-b
bind C-e send-prefix

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'

run '~/.config/tmux/.tmux/plugins/tpm/tpm'
```

- Default powerline config besides setting `TMUX_POWERLINE_STATUS_JUSTIFICATION` and `TMUX_POWERLINE_THEME`
- Default powerline theme with removed segments, nothing crazy
- In my generated default config, status justification was set to center. Based on this [commit](https://github.com/izzygomez/dotfiles/commit/b04c40d127240387812656cc7d00f01e00240dc8) though, it should set it to absolute-centre.

**What I've tried:**
- Setting `status-justify` in tmux.conf and in `config.sh` both exclusively and simultaneously. I've also tried setting the option values with and without double quotes.
- `TMUX_POWERLINE_STATUS_VISIBILITY` 1 and 2
- Reloading config through tpm, leader+R, kill-server, and logging out.
- Reinstalling powerline
- status justify as well as absolute-centre does work properly on default tmux status line
- made sure it wasnt a typo lol "absolute-centre"
- Other powerline config options do work

**Comment by xx4h** [comment]
Hi @jnzigg,

thanks for reporting. This looks like a regression from the new dual-line status feature. This one's on me :grimacing: 

I am working on a fix, shouldn't take too long, but no ETA yet.

As a workaround until it is fixed, you should be able to jump back to 8774dbffc88b73bd43cf8db107b50305360d4a56, by just
```
cd ~/.tmux/plugins/tmux-powerline
git checkout 8774dbffc88b73bd43cf8db107b50305360d4a56
```
