### ISSUE TITLE
separator_foreground_color not working

### ISSUE THREAD

**Issue by curbol** [erikw/tmux-powerline#426]
In the default theme there is this documentation on how to style each segment:

```sh
# * non_default_separator - specify an alternative character for this segment's separator
# * separator_background_color - specify a unique background color for the separator
# * separator_foreground_color - specify a unique foreground color for the separator
```

### Expectation
My interpretation of this is that I should be able to change the color of the separator to a different color than the main segment text.

I'm expecting something like this where the separator is a different color than the text (screenshot from neovim):
<img width="451" alt="image" src="https://github.com/erikw/tmux-powerline/assets/5971687/60cdf413-e538-4b98-9748-966826f09126">

Example segment definition that doesn't work correctly (abbreviated variable names):
```sh
"weather ${BG} ${FG} ${SEPARATOR} ${SEPARATOR_BG} ${SEPARATOR_FG}"
```

### What actually happens
`separator_background_color` and `separator_foreground_color` don't do anything. Instead the separator always uses the colors of `background_color` and `foreground_color`

In the example above, the `${SEPARATOR_BG}` and `${SEPARATOR_FG}` don't appear to do anything. The `${SEPARATOR}` is always the color of `${BG}` and `${FG}`.

<img width="451" alt="image" src="https://github.com/erikw/tmux-powerline/assets/5971687/c7582015-d70f-4f09-9d79-2dbbdfcde017">

From looking at example screenshots, I haven't ever seen a case where the separator is a different color, which leads me to believe this feature isn't working.

**Comment by xx4h** [comment]
You're right, this feature is not working. This is not theme related, it is not working at all. I'll have a look, thanks for reporting :+1:

**Comment by xx4h** [comment]
Tested #427, but would be nice if someone else could give it a try as well.

**Comment by curbol** [comment]
Thanks for the fix. I confirmed that it's working:
<img width="282" alt="image" src="https://github.com/erikw/tmux-powerline/assets/5971687/94307411-4051-4f31-9804-8081c07fefd9">
