### ISSUE TITLE
Bell activity is not styled

### ISSUE THREAD

**Issue by lunks** [erikw/tmux-powerline#429]
I'm not sure if this should be reported here or on powerline it self, but bell activity does not apply the style correctly. You can reproduce by running:

```
sleep 1 && tput bel
```

Then, move away from the window.

<img width="747" alt="Screen Shot 2024-05-25 at 18 25 10" src="https://github.com/erikw/tmux-powerline/assets/91118/315de6ce-cf6d-4789-8a10-b89b59761f59">

**Comment by lunks** [comment]
Solved by adding:

```
set-option -g window-status-bell-style none
```

**Comment by xx4h** [comment]
Also see https://github.com/erikw/tmux-powerline/discussions/342#discussioncomment-8990052
