### ISSUE TITLE
Tmux supported version needs to be updated

### ISSUE THREAD

**Issue by mchouque** [erikw/tmux-powerline#449]
Hello,

I'm dealing with multiple environments and multiple OS versions and in the README, the required version for tmux is incorrect.

> tmux -V >= 2.1

tmux-powerline (in tag v3.0.0) uses a tmux variable called status-format which got introduced in tmux 2.9.

So the requirement for v3.0.0 is at least >= 2.9 (I haven't checked everything but I checked that v2.1.0 works with tmux 2.7).

Regards,
Mathieu

**Comment by xx4h** [comment]
Hi,

thanks for reporting. README is updated.
