### ISSUE TITLE
disappears if status-left-length/right too wide

### ISSUE THREAD

**Issue by ag4ve** [erikw/tmux-powerline#48]
when i had the config as you listed in my .tmux.conf, nothing showed up. you were showing an example, however i think it might be better to find a fairly universal environment variable to determine the area things are displayed in.(possibly $COLUMNS is universal enough?)

btw, it now works for me, but if you need to recreate me not seeing anything in the status with the 60/90, i'm running debian stable xmonad (mainly from cabal but parts from apt), rxvt-unicode (deb).

**Comment by 7h3kk1d** [comment]
Still having this problem and it makes it pretty unusable if myu window is even relatively narrow.

**Comment by ChipWolf** [comment]
Hello from the future, still an issue!
