### ISSUE TITLE
arrows not displayed correctly in terminal.app

### ISSUE THREAD

**Issue by pencilcheck** [erikw/tmux-powerline#70]
I'm currently using Terminal.app running tmux and zsh

After struggling with the bash and path, now it is finally working, but this is what I saw
http://cl.ly/image/2U3b071w0L0y

Even in iTerm2 too
http://cl.ly/image/3f053a2Q0K0U

Pretty ugly, so I went to the preference and check the font I use, I can confirm it is using the patched fonts from vim-powerline "Monaco for Powerline 11pt"

So I'm curious what is happening to the arrows, why are they so small?

**Comment by aminnairi** [comment]
Same there, just leaving a comment for people using Konsole. I had downloaded the Nerd patch fonts for using JetBrains Mono. But I also had downloaded the unpatched JetBrains Mono font which was the one used. Once I switch to the JetBrains Mono Nerd Font in the Konsole settings, everything was showing good, even the arrows from the powerline symbols. Chances are that you didn't switched to the Nerd font yet if you face this issue.

Hope this will help you, stranger from the future!

**Comment by sai5555** [comment]
> Same there, just leaving a comment for people using Konsole. I downloaded the Nerd patch fonts for using JetBrains Mono. But I also had downloaded the unpatched JetBrains Mono font which was the one used. Once I switch to the JetBrains Mono Nerd Font in the Konsole settings, everything was showing good, even the arrows from the powerline symbols. Chances are that you didn't switched to the Nerd font yet if you face this issue.
> 
> Hope this will help you, stranger from the future!

I just use konsole. 
You are right . thanks.
